### ISSUE TITLE
Add option to make RDS publicly accessible

### ISSUE THREAD

**Issue by macobo** [PostHog/deployment#40]
This came up in posthog users chat: https://posthogusers.slack.com/archives/CT7HXDEG3/p1605868648007300

Currently you can't connect to the RDS instance for posthog from outside the VPC. This might however be needed to connect to Metabase/other BI or do some other hackery.

We could add an Parameter to our template to expose RDS to the world. Just need to make sure the user isn't using the default password.

**Comment by bastika** [comment]
Hi @macobo, are there any updates on this issue?
