### ISSUE TITLE
DB Environment variables do not use CloudFormation template parameters

### ISSUE THREAD

**Issue by lharress** [PostHog/deployment#54]
The `DATABASE_URL` environment variable for the ECS Task definition uses hard coded values for username and password, as a result changing the RDS username or password results in a 503.

https://github.com/PostHog/deployment/blob/5980002f3edc2b7edf6bb60b36c154c26c79623a/aws/cloudformation/ecs/posthog.yaml#L691-L692

https://github.com/PostHog/deployment/blob/5980002f3edc2b7edf6bb60b36c154c26c79623a/aws/cloudformation/ecs/posthog.yaml#L735-L736

```
- Name: DATABASE_URL
  Value: !Join ['', ['postgres://', !Ref 'RDSMasterUser', ':', !Ref 'RDSMasterUserPassword', '@', !GetAtt [PosthogDB, Endpoint.Address], ':', !GetAtt [PosthogDB, Endpoint.Port], '/posthog']]
```

Should do the trick for both.

**Comment by macobo** [comment]
Good note! Mind sending a PR our way in return for some swag? :)

**Comment by lharress** [comment]
Sure. All sorted ^
