### ISSUE TITLE
Allow Cloudformation Parameters for ALB to use re-direct

### ISSUE THREAD

**Issue by dshack1** [PostHog/deployment#62]
Hello,

I would like an enhancement to the Cloudformation template to allow ALB to provide a re-direct value for port 80, see below:

 PublicLoadBalancerListener:
    Type: AWS::ElasticLoadBalancingV2::Listener
    Properties:
      DefaultActions:
        - TargetGroupArn: !Ref 'DummyTargetGroupPublic'
          Type: 'forward'
      LoadBalancerArn: !Ref 'PublicLoadBalancer'
      Port: 80
      Protocol: HTTP

Link: https://github.com/PostHog/deployment/blob/master/aws/cloudformation/ecs/posthog.yaml

**Comment by fuziontech** [comment]
Unfortunately we've sunset support for our cloudformation setup. I would check out our new deployment options for PostHog https://posthog.com/docs/self-host
