### ISSUE TITLE
ECS posthog.yml parameter references

### ISSUE THREAD

**Issue by rksm** [PostHog/deployment#9]
Among the parameters specified in `deployment/aws/cloudformation/ecs/posthog.yml` are `EmailUserSSL` and `EmailUserTLS`. In the container definition I see `Ref! 'EmailUseTLS'` and `Ref! 'EmailUseSSL'`.

When deploying the script I get `ValueError: Ref! 'EmailUseSSL' is an invalid value for EMAIL_USE_SSL, expected boolean` and such.

I assume these are typos?

**Comment by fuziontech** [comment]
Great catch here and thanks for the issue!
